apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-pvc
          persistentVolumeClaim:
            claimName: log-output-pv-claim
      containers:
        - name: log-output-add
          image: niksubbo/log-output-add:c3b2678cf19f2e3b12bdc07c25357fe550ac3ffb
          volumeMounts:
            - name: shared-pvc
              mountPath: /app/files
        - name: log-output-get
          image: niksubbo/log-output-get:5cb5ffe0e06340cf61a3268b2ccba2d72bd6b0f8
          volumeMounts:
            - name: shared-pvc
              mountPath: /app/files
