apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: shared-pvc
          persistentVolumeClaim:
            claimName: project-pv-claim
      containers:
        - name: todo-app
          image: niksubbo/todo-app:adb3434fe955a5e9a2106dce4514e6acfaf31e99
          env:
            - name: PORT
              value: "5000"
          volumeMounts:
            - name: shared-pvc
              mountPath: /app/files
